name: Generate RSS

on:
  workflow_dispatch:  # 手动触发保留
  schedule:
    - cron: '*/10 * * * *'  # 每 10 分钟执行一次（UTC 时间）


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run start
      - name: Commit RSS Feed
        run: |
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git add feed.xml
            git commit -m "Update RSS feed" || echo "No changes"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        
